# Generated by Django 4.0.5 on 2022-06-26 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='Вопрос')),
                ('groupid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myTest.questiongroups', verbose_name='Группы вопросов')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время начала тестирования')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Вопрос пройден в данном тестировании')),
                ('result', models.BooleanField(default=False, verbose_name='Правильно отвечен')),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.questions', verbose_name='Номер вопроса')),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.tests', verbose_name='Номер теста')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='QuestAnsws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.answers', verbose_name='Номер ответа')),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.questions', verbose_name='Номер вопроса')),
            ],
            options={
                'verbose_name': 'вопрос-ответ',
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='questionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.questions', verbose_name='Вариант ответа к вопросу'),
        ),
    ]
