# Generated by Django 4.0.5 on 2022-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'verbose_name': 'Вопросы в тесте', 'verbose_name_plural': 'Вопросы в тестах'},
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Тест'),
        ),
    ]
