# Generated by Django 4.0.5 on 2022-06-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myTest', '0002_alter_testquestion_options_alter_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionid',
            field=models.ManyToManyField(through='myTest.TestQuestion', to='myTest.test'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='testid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.test', verbose_name='Тест'),
        ),
    ]
