# Generated by Django 4.0.5 on 2022-06-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTest', '0003_question_questionid_alter_testquestion_testid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questionid',
        ),
        migrations.AlterField(
            model_name='question',
            name='questionid',
            field=models.ManyToManyField(related_name='testid', through='myTest.TestQuestion', to='myTest.test'),
        ),
    ]
