# Generated by Django 4.0.5 on 2022-06-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTest', '0005_test_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerid',
            field=models.ManyToManyField(to='myTest.answer'),
        ),
    ]
