# Generated by Django 4.0.5 on 2022-06-28 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myTest', '0006_question_answerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Результат, %')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время начала тестирования')),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.test', verbose_name='Тест')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат пользователя',
                'verbose_name_plural': 'Результаты пользователей',
            },
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False, verbose_name='Правильно отвечен')),
                ('testquestionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.testquestion', verbose_name='Вопрос теста')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
