# Generated by Django 4.0.5 on 2022-06-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTest', '0008_alter_question_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
    ]
