# Generated by Django 4.0.5 on 2022-06-29 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myTest', '0011_te_quesid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques',
            name='testid',
        ),
        migrations.RemoveField(
            model_name='te',
            name='quesid',
        ),
        migrations.CreateModel(
            name='TeQues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.ques', verbose_name='Ques')),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.te', verbose_name='Tes')),
            ],
        ),
    ]
