# Generated by Django 4.0.5 on 2022-06-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myTest', '0013_teques_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='teques',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teques',
            name='object_id',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
