# Generated by Django 4.0.5 on 2022-06-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTest', '0014_teques_content_type_teques_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teques',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='teques',
            name='object_id',
        ),
    ]
