# Generated by Django 4.0.5 on 2022-07-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTest', '0015_remove_teques_content_type_remove_teques_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ans',
            name='questionid',
        ),
        migrations.AddField(
            model_name='ques',
            name='r_answer',
            field=models.ManyToManyField(to='myTest.ans'),
        ),
    ]
