# Generated by Django 4.0.5 on 2022-07-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myTest', '0017_alter_te_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answerid',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionid',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questionid',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='questionid',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='testid',
        ),
        migrations.AlterField(
            model_name='ans',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Варианты ответа'),
        ),
        migrations.AlterField(
            model_name='teques',
            name='answer',
            field=models.ManyToManyField(to='myTest.ans', verbose_name='Варианты ответа'),
        ),
        migrations.AlterField(
            model_name='teques',
            name='questionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.ques', verbose_name='Вопрос теста'),
        ),
        migrations.AlterField(
            model_name='teques',
            name='testid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.te', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='testquestionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.teques', verbose_name='Вопрос теста'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='testid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTest.te', verbose_name='Тест'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
    ]
